on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            trap 'echo "Deploy failed at line $LINENO"' ERR
            cd ~/${{ github.event.repository.name }} 2>/dev/null || git clone --depth 1 git@github.com:${{ github.repository }}.git ~/${{ github.event.repository.name }} && cd ~/${{ github.event.repository.name }}
            git fetch --prune --depth=1 origin main
            git reset --hard origin/main
            docker compose -f compose.prod.yaml build --pull
            docker compose -f compose.prod.yaml up -d --remove-orphans
